import {
  int,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
  decimal,
  json,
  boolean,
  index,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Market metadata and current state.
 * Stores information about Polymarket markets for quick lookup.
 */
export const markets = mysqlTable(
  "markets",
  {
    id: int("id").autoincrement().primaryKey(),
    polymarketId: varchar("polymarketId", { length: 256 }).notNull().unique(),
    eventId: varchar("eventId", { length: 256 }).notNull(),
    eventName: text("eventName").notNull(),
    marketName: text("marketName").notNull(),
    outcomes: json("outcomes").$type<string[]>().notNull(), // ["Yes", "No"]
    conditionId: varchar("conditionId", { length: 256 }).notNull(),
    enableOrderBook: boolean("enableOrderBook").default(true),
    active: boolean("active").default(true),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (table) => ({
    polymarketIdIdx: index("polymarketId_idx").on(table.polymarketId),
    eventIdIdx: index("eventId_idx").on(table.eventId),
    activeIdx: index("active_idx").on(table.active),
  })
);

export type Market = typeof markets.$inferSelect;
export type InsertMarket = typeof markets.$inferInsert;

/**
 * Market snapshots for trend analysis.
 * Stores hourly snapshots of market state for historical analysis.
 */
export const marketSnapshots = mysqlTable(
  "market_snapshots",
  {
    id: int("id").autoincrement().primaryKey(),
    marketId: int("marketId").notNull(),
    timestamp: timestamp("timestamp").notNull(),
    prices: json("prices").$type<number[]>().notNull(), // [yesPrice, noPrice]
    volume24h: decimal("volume24h", { precision: 20, scale: 8 }),
    momentum: decimal("momentum", { precision: 10, scale: 6 }),
    volatility: decimal("volatility", { precision: 10, scale: 6 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (table) => ({
    marketIdIdx: index("marketId_idx").on(table.marketId),
    timestampIdx: index("timestamp_idx").on(table.timestamp),
  })
);

export type MarketSnapshot = typeof marketSnapshots.$inferSelect;
export type InsertMarketSnapshot = typeof marketSnapshots.$inferInsert;

/**
 * Predictions generated by the prediction engine.
 * Stores all predictions with signals, outcomes, and accuracy metrics.
 */
export const predictions = mysqlTable(
  "predictions",
  {
    id: int("id").autoincrement().primaryKey(),
    marketId: int("marketId").notNull(),
    polymarketId: varchar("polymarketId", { length: 256 }).notNull(),
    predictedOutcome: varchar("predictedOutcome", { length: 64 }).notNull(), // "Yes" or "No"
    predictedProbability: decimal("predictedProbability", {
      precision: 5,
      scale: 4,
    }).notNull(), // 0.0000 to 1.0000
    confidence: decimal("confidence", { precision: 5, scale: 4 }).notNull(),
    signals: json("signals").$type<Record<string, number>>().notNull(), // {momentum: 0.5, sentiment: 0.7, ...}
    signalWeights: json("signalWeights").$type<Record<string, number>>().notNull(), // {momentum: 0.3, sentiment: 0.7}
    actualOutcome: varchar("actualOutcome", { length: 64 }),
    isAccurate: boolean("isAccurate"),
    marketResolved: boolean("marketResolved").default(false),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (table) => ({
    marketIdIdx: index("marketId_idx").on(table.marketId),
    polymarketIdIdx: index("polymarketId_idx").on(table.polymarketId),
    createdAtIdx: index("createdAt_idx").on(table.createdAt),
  })
);

export type Prediction = typeof predictions.$inferSelect;
export type InsertPrediction = typeof predictions.$inferInsert;

/**
 * Notifications for users about market movements and prediction accuracy.
 */
export const notifications = mysqlTable(
  "notifications",
  {
    id: int("id").autoincrement().primaryKey(),
    userId: int("userId").notNull(),
    marketId: int("marketId"),
    type: mysqlEnum("type", [
      "THRESHOLD_CROSSED",
      "MOVEMENT_DETECTED",
      "PREDICTION_RESOLVED",
      "ACCURACY_UPDATE",
    ]).notNull(),
    title: varchar("title", { length: 256 }).notNull(),
    message: text("message").notNull(),
    severity: mysqlEnum("severity", ["INFO", "WARNING", "ALERT"]).default(
      "INFO"
    ),
    isRead: boolean("isRead").default(false),
    metadata: json("metadata").$type<Record<string, unknown>>(),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (table) => ({
    userIdIdx: index("userId_idx").on(table.userId),
    marketIdIdx: index("marketId_idx").on(table.marketId),
    isReadIdx: index("isRead_idx").on(table.isRead),
  })
);

export type Notification = typeof notifications.$inferSelect;
export type InsertNotification = typeof notifications.$inferInsert;

/**
 * Aggregated accuracy metrics for reporting and analysis.
 */
export const accuracyMetrics = mysqlTable(
  "accuracy_metrics",
  {
    id: int("id").autoincrement().primaryKey(),
    period: mysqlEnum("period", ["DAILY", "WEEKLY", "MONTHLY"]).notNull(),
    periodDate: timestamp("periodDate").notNull(),
    totalPredictions: int("totalPredictions").default(0),
    accuratePredictions: int("accuratePredictions").default(0),
    accuracy: decimal("accuracy", { precision: 5, scale: 4 }),
    averageConfidence: decimal("averageConfidence", { precision: 5, scale: 4 }),
    averageProbability: decimal("averageProbability", {
      precision: 5,
      scale: 4,
    }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (table) => ({
    periodIdx: index("period_idx").on(table.period),
    periodDateIdx: index("periodDate_idx").on(table.periodDate),
  })
);

export type AccuracyMetric = typeof accuracyMetrics.$inferSelect;
export type InsertAccuracyMetric = typeof accuracyMetrics.$inferInsert;

/**
 * User watchlist for tracking favorite markets.
 */
export const watchlist = mysqlTable(
  "watchlist",
  {
    id: int("id").autoincrement().primaryKey(),
    userId: int("userId").notNull(),
    marketId: int("marketId").notNull(),
    addedAt: timestamp("addedAt").defaultNow().notNull(),
  },
  (table) => ({
    userIdIdx: index("userId_idx").on(table.userId),
    marketIdIdx: index("marketId_idx").on(table.marketId),
  })
);

export type WatchlistItem = typeof watchlist.$inferSelect;
export type InsertWatchlistItem = typeof watchlist.$inferInsert;

/**
 * API call logs for monitoring and cost tracking.
 */
export const apiLogs = mysqlTable(
  "api_logs",
  {
    id: int("id").autoincrement().primaryKey(),
    service: varchar("service", { length: 64 }).notNull(), // "polymarket", "llm", "aws"
    endpoint: varchar("endpoint", { length: 256 }).notNull(),
    method: varchar("method", { length: 16 }).notNull(), // "GET", "POST", etc.
    statusCode: int("statusCode"),
    responseTime: int("responseTime"), // milliseconds
    errorMessage: text("errorMessage"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (table) => ({
    serviceIdx: index("service_idx").on(table.service),
    createdAtIdx: index("createdAt_idx").on(table.createdAt),
  })
);

export type ApiLog = typeof apiLogs.$inferSelect;
export type InsertApiLog = typeof apiLogs.$inferInsert;

/**
 * User portfolio positions - tracks user's market positions and holdings.
 */
export const portfolioPositions = mysqlTable(
  "portfolio_positions",
  {
    id: int("id").autoincrement().primaryKey(),
    userId: int("userId").notNull(),
    marketId: int("marketId").notNull(),
    outcome: varchar("outcome", { length: 64 }).notNull(),
    quantity: decimal("quantity", { precision: 20, scale: 8 }).notNull(),
    entryPrice: decimal("entryPrice", { precision: 10, scale: 6 }).notNull(),
    currentPrice: decimal("currentPrice", { precision: 10, scale: 6 }),
    entryValue: decimal("entryValue", { precision: 20, scale: 8 }).notNull(),
    currentValue: decimal("currentValue", { precision: 20, scale: 8 }),
    unrealizedPnL: decimal("unrealizedPnL", { precision: 20, scale: 8 }),
    notes: text("notes"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (table) => ({
    userIdIdx: index("userId_idx").on(table.userId),
    marketIdIdx: index("marketId_idx").on(table.marketId),
    userMarketIdx: index("userMarket_idx").on(table.userId, table.marketId),
  })
);

export type PortfolioPosition = typeof portfolioPositions.$inferSelect;
export type InsertPortfolioPosition = typeof portfolioPositions.$inferInsert;

/**
 * Portfolio transactions - tracks all buy/sell transactions.
 */
export const portfolioTransactions = mysqlTable(
  "portfolio_transactions",
  {
    id: int("id").autoincrement().primaryKey(),
    userId: int("userId").notNull(),
    marketId: int("marketId").notNull(),
    type: mysqlEnum("type", ["BUY", "SELL"]).notNull(),
    outcome: varchar("outcome", { length: 64 }).notNull(),
    quantity: decimal("quantity", { precision: 20, scale: 8 }).notNull(),
    price: decimal("price", { precision: 10, scale: 6 }).notNull(),
    totalValue: decimal("totalValue", { precision: 20, scale: 8 }).notNull(),
    notes: text("notes"),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (table) => ({
    userIdIdx: index("userId_idx").on(table.userId),
    marketIdIdx: index("marketId_idx").on(table.marketId),
    typeIdx: index("type_idx").on(table.type),
  })
);

export type PortfolioTransaction = typeof portfolioTransactions.$inferSelect;
export type InsertPortfolioTransaction = typeof portfolioTransactions.$inferInsert;

/**
 * User preferences and settings.
 */
export const userPreferences = mysqlTable(
  "user_preferences",
  {
    id: int("id").autoincrement().primaryKey(),
    userId: int("userId").notNull().unique(),
    theme: mysqlEnum("theme", ["light", "dark"]).default("light"),
    currency: varchar("currency", { length: 3 }).default("USD"),
    notificationsEnabled: boolean("notificationsEnabled").default(true),
    emailNotifications: boolean("emailNotifications").default(false),
    pushNotifications: boolean("pushNotifications").default(true),
    movementThreshold: decimal("movementThreshold", { precision: 5, scale: 2 }).default("5.00"),
    accuracyThreshold: decimal("accuracyThreshold", { precision: 5, scale: 2 }).default("70.00"),
    language: varchar("language", { length: 10 }).default("en"),
    timezone: varchar("timezone", { length: 64 }).default("UTC"),
    showPnL: boolean("showPnL").default(true),
    showUnrealized: boolean("showUnrealized").default(true),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  (table) => ({
    userIdIdx: index("userId_idx").on(table.userId),
  })
);

export type UserPreference = typeof userPreferences.$inferSelect;
export type InsertUserPreference = typeof userPreferences.$inferInsert;

/**
 * Portfolio performance history - aggregated daily metrics.
 */
export const portfolioPerformance = mysqlTable(
  "portfolio_performance",
  {
    id: int("id").autoincrement().primaryKey(),
    userId: int("userId").notNull(),
    date: timestamp("date").notNull(),
    totalValue: decimal("totalValue", { precision: 20, scale: 8 }).notNull(),
    totalInvested: decimal("totalInvested", { precision: 20, scale: 8 }).notNull(),
    totalPnL: decimal("totalPnL", { precision: 20, scale: 8 }),
    pnLPercentage: decimal("pnLPercentage", { precision: 10, scale: 6 }),
    positionCount: int("positionCount").default(0),
    winRate: decimal("winRate", { precision: 5, scale: 4 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
  },
  (table) => ({
    userIdIdx: index("userId_idx").on(table.userId),
    dateIdx: index("date_idx").on(table.date),
    userDateIdx: index("userDate_idx").on(table.userId, table.date),
  })
);

export type PortfolioPerformance = typeof portfolioPerformance.$inferSelect;
export type InsertPortfolioPerformance = typeof portfolioPerformance.$inferInsert;

/**
 * System configuration and settings.
 */
export const systemConfig = mysqlTable("system_config", {
  id: int("id").autoincrement().primaryKey(),
  key: varchar("key", { length: 128 }).notNull().unique(),
  value: text("value").notNull(),
  description: text("description"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SystemConfig = typeof systemConfig.$inferSelect;
export type InsertSystemConfig = typeof systemConfig.$inferInsert;
